nss-fumbling-penguins/nutshell

- src/Gruntfile.js
- src/index.html
- src/scripts/main.js
- src/scripts/registration/UserForms.js
- src/scripts/registration/UserManager.js
Closes #12  [Link](https://github.com/nss-fumbling-penguins/nutshell/issues/12)
- 
```sh
git checkout userForms
```
click sign up button, create new User.  Check that user added to database, and that they are logged in with the right id in session storage. 
click sign up again, fill out form with same user name.  on submit, should display warning that the username is already in use, and to try again. 
click login. log in with another username and password in the database. session storage should update to that user's id. 
new userforms module
userManager refactored to account for promises. 
some additional elements on index.html
> User forms

- src/index.html
- src/scripts/main.js
- src/scripts/registration/UserManager.js
- src/scripts/tasks/TasksInit.js
- src/scripts/viewManager/viewManager.js
Closes #10  [Link](https://github.com/nss-fumbling-penguins/nutshell/issues/10)
this module builds a landing page on page load, and provides methods to build a dashboard upon signup and login, and a signedout view when a user logs out
- 
```sh
git checkout viewManager
```
1.signup a new user.  the user should be logged in on session storage, and the nav should have a logout button and the user's first name
2. click logout.  user should be logged out of session storage, and the logged out view should appear - with a message and the signup and login buttons. 
3. log in a different user, and sign them out. 
4. refresh the page to see the landing page.
> View manager

- src/scripts/friends/addFriend.js
- src/scripts/friends/addFriendForm.js
- src/scripts/friends/clearAddFriendFormField.js
- src/scripts/friends/createFriendElement.js
- src/scripts/friends/friendsInit.js
- src/scripts/friends/friendsListEventHandlers.js
- src/scripts/friends/hideAddFriendModal.js
- src/scripts/friends/index.js
- src/scripts/friends/removeFriend.js
- src/scripts/friends/showAddFriendModal.js
- src/scripts/friends/showFriendsList.js
- src/scripts/main.js
- src/scripts/viewManager/viewManager.js
Closes #7 
adds functionality of the friends list view, user can now add, delete, and see their friends 
```sh
git checkout rm-friends
```
1. make sure you are signed in as a user
1. if user already has friends in the database, they should auto populate as the page loads
1. clicking the add friend button should open a modal were a username can be typed to add
1. type a username from the database and either click submit or hit enter while input field is focused
1. the form should disappear and the friend should now be listed at the bottom of the friends list
1. open the form again to make sure field was cleared
Chat - Levi adding functionality to call the add friend form from chat …
> Rm friends

- src/scripts/friends/showFriendsList.js
- src/scripts/viewManager/viewManager.js
if a user is stored in session storage. They are now automatically presented with their dashboard upon refreshing the page
```sh
git checkout rm-auto-login
```
1. load page
1. if you were signed in. you should now see your dashboard rather than the login page
1. if not signed in, sign in as a user and try refreshing the page
1. you should not be presented with a login page unless you manually log out and refresh page
view modules, and user module
1. Complete README that documents the steps to install the code, how to install any dependencies, or system …
> Rm auto login

- src/package-lock.json
- src/package.json
- src/scripts/friends/createFriendElement.js
- src/scripts/friends/friendsInit.js
- src/scripts/friends/popupFriends.js
- src/scripts/friends/showFriendsList.js
- src/scripts/viewManager/viewManager.js
- src/styles/styles.css
made friends list a popup from the navbar
```sh
git checkout rm-friends-list-popup
```
1. load page
1. check that show friends list button will hide and show friends list popup
nav bar
friends list
1. The project must be able to run …
> Rm friends list popup

- src/scripts/friends/popupFriends.js
- src/scripts/friends/showFriendsList.js
- src/styles/styles.css
refactored popup friends list to be more clear that it is a popup
```sh
git checkout rm-friends-list-tooltip
```
navbar
friends list
1. The project must be able to run fully, and without errors, on each teammate's system.
1. …
> refactored friends popup to style more clearly

- src/scripts/friends/friendsInit.js
- src/scripts/friends/popupEventHandler.js
- src/scripts/friends/popupFriends.js
- src/scripts/viewManager/viewManager.js
per clients request, the friends list is no longer a popup
```sh
git checkout rm-friends-out-of-popup
```
1. load page
1. show friends list button should no longer be in the nav bar
1. friends list should now show up as a separate component
navbar
friends list
dashboard view
1. Every method must be documented with purpose and argument list - which itself must …
> friends is now a component again

- src/scripts/friends/addFriend.js
fixed error when adding a friend was trying to call removed popup object
```sh
git checkout rm-add-friend-bug
```
1. try to add a friend from chat and from friend list
1. make sure you do not get an error referencing the old friends popup list code
friends list
chat
dashboard view
modals 
1. Every method must be documented with purpose and argument list - …
> fixed error when adding friend

- src/scripts/chat/buildChat.js
- src/scripts/chat/printChat.js
- src/scripts/chat/retrieveChat.js
commented chat code
refactored slightly for efficiency
- 
```sh
git checkout chat
```
1. no changes to functionality, just attempt to send and edit messages
* chat
1. The project must be able to run fully, and without errors, on …
> refactored and commented the chat code

- src/scripts/registration/UserForms.js
- src/scripts/viewManager/viewManager.js
- src/styles/styles.css
- 
```sh
git checkout moreStyles
```
make sure that the dashboard appears properly on screen
-login and signup forms styled
dashboard styled
*
> More styles

- src/scripts/events/buildEventCard.js
- src/scripts/events/eventView.js
- src/scripts/viewManager/viewManager.js
- src/styles/styles.css
added filter and reduce methods in eventView to find which event is happening next, then style accordingly
- 
on page load or when an event is added, event view should be rebuilt with next event highlighted and in bolder/ bigger text
```sh
git checkout patrick
```
event div
* 
1. Every method must be documented with purpose and argument list - which itself …
> function to target next event in que and added styling to said event

- src/scripts/tasks/taskView.js
Refactored tasks view to have the classes as specified in the group meeting for refactoring
```sh
git checkout rm-refactor-tasks-with-classes
```
tasks
1. The project must be able to run fully, and without errors, on each teammate's …
> Rm refactor tasks with classes

- src/scripts/friends/showFriendsList.js
refactored friends view to include classes as specified in group meeting
```sh
git checkout rm-refactor-friends-with-classes
```
1. load up page
1. make sure components in the friends div have the classes specified in the slack message
friends view
1. Every method must be documented with purpose and argument list - which itself must contain a short purpose …
> added classes to friends view

- src/scripts/events/eventView.js
> added classes to the events

- src/styles/styles.css
thins out headers to provide more space for content. 
```sh
git checkout fixHeaders
```
changed margin of h3s inside headers to .25em
> made component headers smaller

- src/scripts/friends/addFriend.js
adding a username as a friend that doesn't exist no longer throws an error in the console. this new code now manually checks to see if the user exists and throws an alert if user doesn't exist.
```sh
git checkout rm-fix-add-friend-bug
```
1. run website
1. try to add a friend that doesn't exist in the database
1. there should now be an alert telling you they don't exist
1. try to add a friend that does exist
1. friend should still be added as a friend
friends list
1. Complete README that documents the steps to install the code, how to install any …
> fixed error in add friend code

- src/styles/styles.css
```sh
git checkout loggedOutButton
```
This just adds the orange styles to the log in button on logged out view
> fixed login button style on logged-out view

- README.md
added readme for project
```sh
git checkout rm-readme
```
1. Literally no code has been changed. But if you want you can look at the readme file.
readme
1. The project must be able to run fully, and without errors, on each …
> filled in readme

- src/scripts/tasks/TaskCardEventHandlers.js
- src/scripts/tasks/TaskFormButtons.js
- src/scripts/tasks/editTaskForm.js
edited task creation and edit forms to auto focus on startup, as well as accepting the enter key as a form submission initiator as long as one of the forms fields is in focus
```sh
git checkout rm-task-form-auto-focus
```
1. create and edit tasks
1. on each form make sure the title field is auto focused on startup
1. on each form try to use enter instead of clicking submit
1. form should otherwise popup and submit information as normal
tasks forms and view
1. Complete README that documents the steps to install the code, how to install any dependencies, …
> edited forms to accept enter as input

- src/scripts/chat/printChat.js
- src/styles/styles.css
- removed bug in chat of allowing multiple edit boxes
- minor styling fix
```sh
git checkout chat
```
1. try to open multiple edit boxes
* chat
> fixed bug of creating multiple edit inputs | minor styling

- src/scripts/friends/addFriend.js
fixed a bug where duplicates of the same friend could be added
```sh
git checkout rm-duplicate-friends-bug
```
1. checkout branch
1. go to page
1. try to add a friend who is already your friend
1. you should get a notification saying they are already your friend
1. a new friend object should NOT be created in the database
1. try to add a friend you are not already friends with
1. friend should be created and added to database as normal
friends list
api
1. Complete README that documents the steps to install the code, how to install any dependencies, or …
> fixed bug where duplicate friends could be created

- src/styles/styles.css
- 
```sh
git checkout <feature_branch>
```
* 
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
> first commit

- src/scripts/viewManager/viewManager.js
- 
```sh
git checkout <feature_branch>
```
* 
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
> added comments

- src/scripts/events/buildEventCard.js
- src/styles/styles.css
added styling in event builder to make events posted by other users italicized and with cornsilk background color
- 
```sh
git checkout patrick
```
event styling
* 
1. The project must be able to run fully, and without errors, on …
> styling for events posted by other users
